### ISSUE TITLE
Plugin causes errors with ASGI lifespan protocol

### ISSUE THREAD

**Issue by simonw** [simonw/datasette-debug-asgi#1]
With this:

`uvicorn.run(ds.app(), host=host, port=port, log_level="info", lifespan="on")`

The server failed to start with this error:

```
INFO:     Started server process [68849]
INFO:     Waiting for application startup.
ERROR:    Exception in 'lifespan' protocol
Traceback (most recent call last):
  File ".../uvicorn/lifespan/on.py", line 48, in main
    await app(scope, self.receive, self.send)
  File ".../uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File ".../datasette_debug_asgi.py", line 9, in wrapped_app
    if scope["path"] == "/-/asgi-scope":
KeyError: 'path'
```
_Originally posted by @simonw in https://github.com/simonw/datasette/issues/873#issuecomment-651193131_

**Comment by simonw** [comment]
Tricky to write a test for this, since using `httpx` as an ASGI client doesn't trigger lifespan events: https://github.com/encode/httpx/issues/350

**Comment by simonw** [comment]
From that thread, https://github.com/florimondmanca/asgi-lifespan aims to solve this. I can add that as a test dependency.
